# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 58afcbd814bc666ff0da6e963902baecb019aebfb040b1e8b32f21b3b948b46d553fe534796f515595c6f40b878c92d9cd7c7a04f9a5f8c93a71a05cb885aa1e

test:
  secret_key_base: 5c76b41b597322ff35c7d9848d8ca2db0b4989b93c08d9fa2a3f7bd66802b1afce6ad2744857f95ec0072f2d1f1a0cbf23bb1ca5fc3b435b340900f6eb050b47

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
